describe('For todomvc on emberjs', ()=>{
    beforeEach(()=>{
        cy.visit('https://todomvc.com/examples/emberjs/')
    })
    it('testing user workflow', ()=>{
       cy.get('#new-todo')
            .should('have.text','')
            .should('have.value', '')
        cy.get('#new-todo')
            .type('a{enter}')
            .type('b{enter}')
            .type('c{enter}')
        cy.get('#todo-list li')
            .first().should('contain', 'a')
            .next().should('contain', 'b')
            .next().should('contain', 'c')
        cy.get('#todo-list label').should('have.length', '3')

        cy.get('#todo-list label').contains('b').dblclick()
        cy.get('.editing ').type('{selectall}{backspace}b*').press_enter()
        cy.get('#todo-list label').should('have.length', '3')

        cy.get('.toggle').eq(1).click()
        cy.get('.completed').should('contain', 'b*')
        cy.get('#todo-list label').should('have.length', '3')

        cy.get('button').eq(1)
            .invoke('show')
            // .click({force: true})
            .click()
        cy.get('#todo-list li')
            .first().should('contain', 'a')
            .next().should('contain', 'c')
        cy.get('#todo-list label').should('have.length', '2')

        cy.get('#todo-list label').contains('a').dblclick()
        cy.get('.editing ')
            .type('{selectall}{backspace}a*{esc}')
        cy.get('#todo-list li')
            .first().should('contain', 'a')
            .next().should('contain', 'c')
        cy.get('#todo-list label').should('have.length', '2')

        cy.get('.destroy').eq(1)
            .invoke('show').click()
        cy.get('#todo-list li')
            .first().should('contain', 'a')
        cy.get('#todo-list label').should('have.length', '1')
    })
})